import pytest
import math

from unittest.mock import MagicMock
from core.Section import Section

@pytest.fixture
def mock_propeller():
    """Create a mock object for the Propeller"""
    mock = MagicMock()
    mock.blade_count = 2
    mock.rotor_diameter = 1
    mock.rho = 1.225  # Air density
    return mock

@pytest.fixture
def mock_airfoil():
    """Create a mock object for the aerodynamic airfoil (profil)"""
    mock = MagicMock()
    mock.getCl.return_value = 1.0
    mock.getCd.return_value = 0.01
    return mock

@pytest.fixture
def section(mock_airfoil, mock_propeller):
    """Initialize a section with the mocks."""
    return Section(mock_airfoil, radius=0.3, width=0.05, pitch=math.radians(10), chord=0.1, propeller=mock_propeller)

def test_initialization(section):
    """Test the initialization of the section's attributes"""
    assert section.radius == 0.3
    assert section.width == 0.05
    assert section.chord == 0.1
    assert section.alpha == 0.0
    assert section.Cl == 0.0
    assert section.Cd == 0.0

def test_airfoil_section_forces(section):
    """Test the calculation of lift and drag coefficients"""
    CT, CQ = section.airfoil_section_forces(math.radians(5))
    assert CT == pytest.approx(0.99, rel=1e-1)  # Approximate values
    assert CQ == pytest.approx(0.09, rel=1e-1)

def test_prandtl_loss_factor(section):
    """Test the Prandtl loss factor"""
    F = section.prandtl_loss_factor(math.radians(5))
    print("%s %s %s"%(section.radius, section.propeller.rotor_diameter, section.propeller.rotor_diameter))
    assert 0 < F <= 1  # Checks that the factor is valid

def test_froude_induction_factors(section):
    """Test the Froude induction factors"""
    a, t = section.froude_induction_factors(math.radians(5))
    assert -2 < a < 1
    assert -2 < t < 1

def test_phi_function(section):
    """Test the phi function"""
    phi = section.phi_function(math.radians(5), omega=100, v_inf=10)
    assert isinstance(phi, float)  # Cheskcs

def test_forces(section):
    """Test the forces generated by the section"""
    T, Q = section.forces(math.radians(5), v_infini=0, omega=100)
    assert T > 0  # Thrust should be positive !!
    assert Q > 0  # Torque should be positive!
